{% set name = "apache-airflow-providers-docker" %}
{% set version = "3.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_docker-{{ version }}.tar.gz
  sha256: 9d3ab311b48a923ddc18d5c36768ad6c8f96266053c664862061c8f8d6be5bb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.7.0
    - docker-py >=6
    - python-dotenv >=0.21.0
    - requests >=2.27.0,<2.32.0

test:
  imports:
    - airflow.providers.docker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-docker for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/docker/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-docker/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
