{% set name = "apache-airflow-providers-docker" %}
{% set version = "3.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_docker-{{ version }}.tar.gz
  sha256: 2a6794597a954a9d0af6cb263ce34b1a4d6c30cd6f407dcba5273947b3edd060

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.dev0
    - apache-airflow >=2.8.0
    - docker-py >=7.1.0
    - python-dotenv >=0.21.0

test:
  imports:
    - airflow.providers.docker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-docker for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/docker/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-docker/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
