{% set name = "apache-airflow-providers-docker" %}
{% set version = "3.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_docker-{{ version }}.tar.gz
  sha256: c1e95491609490d5954e8d733566ea4e0e2a565befd3e089964d741c699ac174

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.7.0
    - docker-py >=7.1.0
    - python-dotenv >=0.21.0
    - requests >=2.27.0,<2.32.0

test:
  imports:
    - airflow.providers.docker
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-docker for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/docker/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-docker/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
