context:
  name: apache-airflow-providers-docker
  version: "4.6.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_docker-${{ version }}.tar.gz
  sha256: 9cfe6f549f08ef1c6b3d75d437004b07a2afd57b15b5637c7103cd74b66de859

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==4.0.2
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.10.1
    - docker-py >=7.1.0
    - python-dotenv >=0.21.0

tests:
  - python:
      imports:
        - airflow.providers.docker
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-docker for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-docker/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
